[manager]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
sort_translit = true
linemode = "lineui"
show_hidden = true
show_symlink = true
mouse_events = [
  "click",
  "scroll",
  "touch",
  "move",
  "drag"
]
title_format = ""

[preview]
wrap = "yes"
tab_size = 4
image_filter = "catmull-rom"
image_quality = 75
sixel_fraction = 13

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[plugin]
prepend_previewers = [
  { name = "*.md", run = "mdcat" },
]
